# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-19 13:23
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Behaviour',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('behaviour', models.TextField()),
                ('behaviour_type', models.CharField(choices=[(1, 'individual behaviour'), (2, 'group behaviour')], max_length=2)),
                ('points', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('reward', models.TextField(blank=True)),
                ('reward_type', models.CharField(choices=[(1, 'individual behaviour'), (2, 'group behaviour')], max_length=2)),
                ('points', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
