# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-23 23:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('behaviour', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BehaviourRupeeReward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('rupee', models.CharField(choices=[(1, b'ruby'), (2, b'sapphire'), (3, b'emerald'), (4, b'amethyst')], max_length=2)),
                ('amount', models.IntegerField()),
                ('behaviour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rupees', to='behaviour.Behaviour')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RewardRupeeCost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('rupee', models.CharField(choices=[(1, b'ruby'), (2, b'sapphire'), (3, b'emerald'), (4, b'amethyst')], max_length=2)),
                ('amount', models.IntegerField()),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rupees', to='behaviour.Reward')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
