# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-23 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('behaviour', '0002_behaviourrupeereward_rewardrupeecost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='behaviour',
            name='points',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
