# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 09:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20160531_0913'),
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInWorld',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.World')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
