# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 11:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0002_userinworld'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinworld',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worlds', to='user.User'),
        ),
        migrations.AlterField(
            model_name='userinworld',
            name='world',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamemasters', to='world.World'),
        ),
    ]
