# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0003_auto_20160531_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='world',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
