# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-01 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0004_auto_20160531_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='world',
            name='course_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='world',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
