# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-10 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0005_auto_20160901_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorldRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('rule', models.TextField()),
                ('points', models.IntegerField()),
                ('rule_type', models.CharField(choices=[(1, b'houding'), (2, b'functioneren binnen het team'), (3, b'kennisontwikkeling'), (4, b'verantwoording')], max_length=2)),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='world.World')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
