# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-15 16:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0006_worldrule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worldrule',
            name='world',
        ),
        migrations.DeleteModel(
            name='WorldRule',
        ),
    ]
