# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-08-21 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0007_auto_20161015_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='world',
            name='trello_user_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
