# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0002_useringuild'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guild',
            name='world',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guilds', to='world.World'),
        ),
        migrations.AlterField(
            model_name='useringuild',
            name='guild',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='guild.Guild'),
        ),
        migrations.AlterField(
            model_name='useringuild',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guilds', to='user.User'),
        ),
    ]
