# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-27 11:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0001_initial'),
        ('guild', '0003_auto_20160531_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuildQuest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quests', to='guild.Guild')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guilds', to='quest.Quest')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
