# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-27 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0004_guildquest'),
    ]

    operations = [
        migrations.AddField(
            model_name='guildquest',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
