# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-31 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0004_questobjective_completed'),
        ('guild', '0005_guildquest_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuildQuestObjective',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('completed', models.BooleanField(default=False)),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='guild.Guild')),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guilds', to='quest.QuestObjective')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
