# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-31 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20160603_1329'),
        ('guild', '0006_guildquestobjective'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuildObjective',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('points', models.IntegerField()),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='user.User')),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objective', to='guild.Guild')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='guildquestobjective',
            name='guild',
        ),
        migrations.RemoveField(
            model_name='guildquestobjective',
            name='objective',
        ),
        migrations.DeleteModel(
            name='GuildQuestObjective',
        ),
    ]
