# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-31 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0007_auto_20160831_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guildobjective',
            name='guild',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='guild.Guild'),
        ),
    ]
