# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-31 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0008_auto_20160831_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guildobjective',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='guildobjective',
            name='description',
        ),
        migrations.RemoveField(
            model_name='guildobjective',
            name='due_date',
        ),
        migrations.AddField(
            model_name='guildobjective',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guildobjective',
            name='objective',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guildobjective',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='guildobjective',
            name='points',
            field=models.PositiveIntegerField(),
        ),
    ]
