# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-31 16:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20160603_1329'),
        ('guild', '0009_auto_20160831_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='guildobjective',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guildobjective',
            name='completed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='user.User'),
        ),
    ]
