# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-26 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0013_guildobjectiveassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='guildquest',
            name='grade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
