# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-27 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0014_guildquest_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guildquest',
            name='grade',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
