# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-07 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0017_auto_20161006_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guildhistoryupdate',
            name='action_type',
            field=models.CharField(choices=[(1, b'added task'), (2, b'removed task'), (3, b'assigned'), (4, b'remove assigned'), (5, b'completed'), (6, b'remove completed'), (7, b'graded'), (8, b'regraded'), (9, b'completed assessment'), (10, b'remove completed assessment')], max_length=2),
        ),
    ]
