# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-07 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0018_auto_20161007_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='guildhistoryupdate',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
