# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-10 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0019_guildhistoryupdate_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='guild',
            name='accepted_rules',
            field=models.BooleanField(default=False),
        ),
    ]
