# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-14 15:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0021_guildrule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guildrule',
            old_name='importance',
            new_name='points',
        ),
    ]
