# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-15 18:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20160922_1707'),
        ('guild', '0022_auto_20161014_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuildRuleEndorsment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('week', models.IntegerField()),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endorsed_rule', to='guild.GuildRule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endorsed_user', to='user.User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
