# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-15 18:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0023_guildruleendorsment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guild',
            name='accepted_rules',
        ),
    ]
