# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-19 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0026_auto_20161015_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guildhistoryupdate',
            name='action_type',
            field=models.CharField(choices=[(1, 'added task'), (2, 'removed task'), (3, 'assigned'), (4, 'remove assigned'), (5, 'completed'), (6, 'remove completed'), (7, 'graded'), (8, 'regraded'), (9, 'completed assessment'), (10, 'remove completed assessment')], max_length=2),
        ),
        migrations.AlterField(
            model_name='guildrule',
            name='rule_type',
            field=models.CharField(choices=[(1, 'houding'), (2, 'functioneren binnen het team'), (3, 'kennisontwikkeling'), (4, 'verantwoording')], max_length=2),
        ),
    ]
