# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-24 11:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0027_auto_20161019_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGuildRupees',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('rupee', models.CharField(choices=[(1, b'ruby'), (2, b'sapphire'), (3, b'emerald'), (4, b'amethyst')], max_length=2)),
                ('amount', models.IntegerField()),
                ('user_in_guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rupees', to='guild.UserInGuild')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
