# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-26 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0028_userguildrupees'),
    ]

    operations = [
        migrations.AddField(
            model_name='guildruleendorsment',
            name='strength',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
