# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-26 12:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0029_guildruleendorsment_strength'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guildruleendorsment',
            old_name='strength',
            new_name='rating',
        ),
    ]
