# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-26 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0030_auto_20161026_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='guild',
            name='trello_board',
            field=models.TextField(blank=True, null=True),
        ),
    ]
