# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-27 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0031_guild_trello_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='guild',
            name='trello_done_list',
            field=models.TextField(blank=True, null=True),
        ),
    ]
