# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-27 13:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0032_guild_trello_done_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guildhistoryupdate',
            name='guild',
        ),
        migrations.RemoveField(
            model_name='guildhistoryupdate',
            name='user',
        ),
        migrations.RemoveField(
            model_name='guildobjective',
            name='completed_by',
        ),
        migrations.RemoveField(
            model_name='guildobjective',
            name='guild',
        ),
        migrations.RemoveField(
            model_name='guildobjectiveassignment',
            name='objective',
        ),
        migrations.RemoveField(
            model_name='guildobjectiveassignment',
            name='user',
        ),
        migrations.DeleteModel(
            name='GuildHistoryUpdate',
        ),
        migrations.DeleteModel(
            name='GuildObjective',
        ),
        migrations.DeleteModel(
            name='GuildObjectiveAssignment',
        ),
    ]
