# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-08-30 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0033_auto_20170127_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='guild',
            name='trello_legenda_list',
            field=models.TextField(blank=True, null=True),
        ),
    ]
