# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-30 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questobjective',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
