# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-31 13:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0002_questobjective_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questobjective',
            name='completed',
        ),
    ]
