# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0003_auto_20160531_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
