# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-31 15:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0005_auto_20160831_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questobjective',
            old_name='description',
            new_name='objective',
        ),
    ]
