# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-08 13:13
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0006_auto_20160831_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='questobjective',
            name='objective',
            field=tinymce.models.HTMLField(default=''),
            preserve_default=False,
        ),
    ]
