# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-21 13:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0007_auto_20160908_1313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quest',
            old_name='frontend_development',
            new_name='techniek',
        ),
        migrations.RenameField(
            model_name='quest',
            old_name='visual_interface_design',
            new_name='visual_design',
        ),
        migrations.RemoveField(
            model_name='quest',
            name='content_management',
        ),
        migrations.RemoveField(
            model_name='quest',
            name='project_management',
        ),
    ]
