# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-22 13:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0008_auto_20160921_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questobjective',
            name='points',
        ),
    ]
