# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-22 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0009_remove_questobjective_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='moodle_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
