# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-02 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0011_quest_gradable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='gradable',
            field=models.BooleanField(default=False),
        ),
    ]
