# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-30 14:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0012_auto_20161002_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quest',
            name='experience',
        ),
    ]
