# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 08:47
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('uid', models.TextField()),
                ('studentNumber', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('initials', models.TextField()),
                ('first_name', models.TextField()),
                ('surname', models.TextField()),
                ('gender', models.PositiveIntegerField(choices=[(0, 'male'), (1, 'female')], default=0)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
