# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 12:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20160531_0913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='studentNumber',
            new_name='student_number',
        ),
    ]
