# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20160531_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(max_length=20),
        ),
    ]
