# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-08 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20160603_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='surname_prefix',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
