# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-22 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20160908_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='surname_prefix',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
