# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-08 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20160922_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='initials',
            field=models.CharField(max_length=15),
        ),
    ]
