# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-22 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20161208_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='student_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
