# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-07-05 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20170322_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='initials',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
