# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-25 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20170705_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
