# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-30 18:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20170825_1250'),
        ('user', '0013_auto_20170826_1327'),
    ]

    operations = [
    ]
