# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-08-30 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_hash',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
    ]
