# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-19 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='rule_type',
            field=models.CharField(choices=[(1, 'houding'), (2, 'functioneren binnen het team'), (3, 'kennisontwikkeling'), (4, 'verantwoording')], max_length=2),
        ),
    ]
